### PR TITLE
Improve language in README.md

### PR DESCRIPTION
**Pull request by cmsflash**

### CODE REVIEW

**Comment by SUNJIANZHI** [comment]
which part confuses you? Unclear in actuarial modelling?

**Comment by cmsflash** [comment]
> which part confuses you? Unclear in actuarial modelling?

I improved the grammar and language use of `README.md`. See the files changed tab for the details.

**Comment by cmsflash** [comment]
Hi @SUNJIANZHI, could you review this PR?

**Review by SUNJIANZHI — APPROVED** [review]
Fine

**Pull request merged**
